version: "3.8"
services:
  pocketbase:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: klokk-backend
    restart: always
    ports:
      - 8090
    volumes:
      - pb_data:/pb/pb_data
    environment:
      - POCKETBASE_PORT_NUMBER=8090
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - WHSEC=${WHSEC}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_LIFETIME_PRICE_ID=${STRIPE_LIFETIME_PRICE_ID}
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8090/_/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  pb_data: {}